# Generated by Django 2.2.5 on 2020-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='images/')),
                ('upscaling', models.CharField(choices=[('s', 'Small'), ('l', 'Large'), ('ln', 'Large(noise cancelling)'), ('el', 'Enchance Large')], default='el', max_length=128)),
            ],
        ),
    ]
